/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Block: typeof import('./src/components/ui/auto/box')['Block']
  const Button: typeof import('./src/components/ui/auto/button')['Button']
  const Flex: typeof import('./src/components/ui/auto/box')['Flex']
  const Font_CoveredByYourGrace: typeof import('./src/components/ui/font/index')['Font_CoveredByYourGrace']
  const Font_MochiyPopPOne: typeof import('./src/components/ui/font/index')['Font_MochiyPopPOne']
  const Font_Montserrat: typeof import('./src/components/ui/font/index')['Font_Montserrat']
  const Grid: typeof import('./src/components/ui/auto/box')['Grid']
  const LoaderInIconify: typeof import('./src/lib/iconsLoader')['LoaderInIconify']
  const NextFontSources: typeof import('./src/components/ui/font/index')['NextFontSources']
  const NextImage: typeof import('next/image')['default']
  const NextLink: typeof import('next/link')['default']
  const NextScript: typeof import('next/script')['default']
  const React: typeof import('react')['default']
  const Spartan: typeof import('./src/components/ui/font/index')['Spartan']
  const buttonVariants: typeof import('./src/components/ui/auto/button')['buttonVariants']
  const cn: typeof import('./src/lib/utils')['cn']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const name: typeof import('./src/components/ui/auto/box')['name']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FC } from 'react'
  import('react')
  // @ts-ignore
  export type { Metadata, ResolvingMetadata } from 'next'
  import('next')
}
