/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Accordian: typeof import('./src/components/ui/auto/accordian')['Accordian']
  const Block: typeof import('./src/components/ui/auto/box')['Block']
  const Button: typeof import('./src/components/ui/auto/button')['Button']
  const Flex: typeof import('./src/components/ui/auto/box')['Flex']
  const Font_CoveredByYourGrace: typeof import('./src/components/ui/auto/font')['Font_CoveredByYourGrace']
  const Font_MochiyPopPOne: typeof import('./src/components/ui/auto/font')['Font_MochiyPopPOne']
  const Font_Montserrat: typeof import('./src/components/ui/auto/font')['Font_Montserrat']
  const Grid: typeof import('./src/components/ui/auto/box')['Grid']
  const MyButton: typeof import('./src/components/ui/auto/myButton')['MyButton']
  const NextFontSources: typeof import('./src/components/ui/auto/font')['NextFontSources']
  const NextImage: typeof import('next/image')['default']
  const NextLink: typeof import('next/link')['default']
  const NextScript: typeof import('next/script')['default']
  const React: typeof import('react')['default']
  const Spartan: typeof import('./src/components/ui/auto/font')['Spartan']
  const StyledDisplayKVPair: typeof import('./src/components/ui/auto/card')['StyledDisplayKVPair']
  const StyledDisplayKVPair_forGrid: typeof import('./src/components/ui/auto/card')['StyledDisplayKVPair_forGrid']
  const StyledTabHeader: typeof import('./src/components/ui/auto/card')['StyledTabHeader']
  const UTC_TIME: typeof import('./src/lib/utils')['UTC_TIME']
  const buttonVariants: typeof import('./src/components/ui/auto/button')['buttonVariants']
  const cn: typeof import('./src/lib/utils')['cn']
  const createRef: typeof import('react')['createRef']
  const daysRemaining: typeof import('./src/lib/utils')['daysRemaining']
  const estimatedXEN: typeof import('./src/lib/utils')['estimatedXEN']
  const formatUnits: typeof import('./src/lib/utils')['formatUnits']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const myButtonVariants: typeof import('./src/components/ui/auto/myButton')['myButtonVariants']
  const name: typeof import('./src/components/ui/auto/box')['name']
  const progressDays: typeof import('./src/lib/utils')['progressDays']
  const startTransition: typeof import('react')['startTransition']
  const toDecimal: typeof import('./src/lib/utils')['toDecimal']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useContracts: typeof import('./src/hooks/useXen')['useContracts']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useFormattedNumberInputBind: typeof import('./src/hooks/common')['useFormattedNumberInputBind']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInputBind: typeof import('./src/hooks/common')['useInputBind']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const useXenStatus: typeof import('./src/hooks/useXen')['useXenStatus']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FC, PropsWithChildren, ReactNode } from 'react'
  import('react')
  // @ts-ignore
  export type { Metadata, ResolvingMetadata } from 'next'
  import('next')
}
