import '@/styles/globals.css'

import { PropsWithChildren } from 'react'

import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Taiko Meme',
  description: 'Generated by create next app'
}

// https://nextjs.org/docs/app/building-your-application/optimizing/fonts#with-tailwind-css
import { NextFontSources } from '@/components/ui/font/index'
const { mochiy_pop_one, montserrat, covered_by_your_grace } = NextFontSources

import { Header } from '@/components/page-header/header'
import { RootProvider } from '@/context/RootProvider'
import { Footer } from '@/components/footer'

type WithChildComponent = React.FC<PropsWithChildren>

const bgUrl = '/sources/bg.png'
const bgAtmosUrl = '/sources/atmosphere.png'

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${mochiy_pop_one.variable} ${covered_by_your_grace.variable}`}
    >
      <body>
        <RootProvider>
          <Layout>{children}</Layout>
        </RootProvider>
        {/* <TailwindIndicator /> */}
      </body>
    </html>
  )
}

const Layout: WithChildComponent = ({ children }) => {
  return (
    <React.Fragment>
      <Background className="absolute -z-10" />
      <div
        className={cn(
          'h-screen',
          'xs:mx-[16px] lg:mx-[120px]',
          'xs:pt-[16px] lg:pt-[20px]'
        )}
      >
        <Header
          className={cn(
            'xs:h-[60px] lg:h-[74px]',
            'xs:mb-[24px] lg:mb-[80px]',
            'rounded-[60px]',
            'backdrop-blur-[24px]',
            'bg-white bg-opacity-20'
          )}
        />
        {children}
      </div>
      <Footer
        className={cn(
          'text-white bg-black',
          'xs:rounded-t-[20px] lg:rounded-t-[40px]',
          'lg:flex items-center lg:justify-between',
          'xs:grid gap-3 place-content-center',
          'xs:h-[102px] lg:h-[80px]',
          'py-[24px]',
          'xs:px-[85px] lg:px-[120px]'
        )}
        logoContainerClass="xs:justify-center"
      />
    </React.Fragment>
  )
}

const Background: FC<{ className?: string }> = ({ className }) => {
  return (
    <React.Fragment>
      <div className={cn('', className)}>
        <div
          style={{ backgroundImage: `url(${bgUrl})` }}
          className={cn(
            'fixed bg-no-repeat',
            'w-full h-[110vh]',
            'bg-cover bg-center'
          )}
        />
        <div
          style={{ backgroundImage: `url(${bgAtmosUrl})` }}
          className={cn(
            'fixed bg-no-repeat',
            'w-[120vw] h-[130vh]',
            'bg-cover xs:bg-center lg:bg-[center_right_150px]'
          )}
        />
      </div>
    </React.Fragment>
  )
}
